### ISSUE TITLE
regexp.MustCompile() performance

### ISSUE THREAD

**Issue by missinglink** [timonmasberg/address-formatter#12]
Heya,

Looking though the code today I noticed that the calls to `regexp.MustCompile()` are inline.

Compiling the regular expressions represents a significant cost of a match, this is why the `compile` and `match/replace` calls are seperated in Go.

Moving the compile step up into the package scope (so they are run once on init) will result in a performance benefit, especially for functions like `getRenderInput` which are called often.

**Comment by timonmasberg** [comment]
Hi, thanks for your comment. This is actually my first go project, so I appreciate your feedback! I wonder if the go compiler does some optimization here if you use MustCompile with a static string? But nevertheless, I think it is better practice to move them into the package scope. I will see how I handle the replacement expressions in the address formatter. Will probably do that next weekend. Thanks again.

**Comment by missinglink** [comment]
Hi Timon, I think in your case maybe it's not such a big deal but there wouldn't be any optimisations for using a static string.

What's going on [under the hood](https://cs.opensource.google/go/go/+/refs/tags/go1.19.3:src/regexp/regexp.go;drc=d5de62df152baf4de6e9fe81933319b86fd95ae4;l=173) is that the string 'pattern' is being converted into a non-deterministic finite state automaton, and possibly simplified into a deterministic automaton. This requires parsing the pattern string and converting it to a graph type structure in memory which allows very fast lookups, in your case the automaton would likely be small and reasonably fast to build. It's still a good best-practise to call `Compile()` only once.

All the best
-P

**Comment by timonmasberg** [comment]
https://github.com/timonmasberg/address-formatter/commit/cfdd1690fcfd05ea409e64118d7cd846477a0694
